### ISSUE TITLE
cannot get Csrf Secret

### ISSUE THREAD

**Issue by navalinovian** [adonisjs/shield#36]
Hi!
I'm currently developing a rest api application using adonisjs. I'm having a problem using CSRF protection, I'm getting an error when making a request. Do I need to add something in my code? Thanks in advance

## Package version
`"@adonisjs/shield": "^7.0.7",`

## Node.js and npm version
`Node : v16.13.2 | npm : 8.3.1`

## Sample Code (to reproduce the issue)

- controller/CategoriesController.ts
`public async index({response,}:HttpContextContract ) {
        const category = await Category.all();
        return response.status(200)
        .json({code:200,
            statu:'success',
            data:category
        });
    }
`

- terminal
`[1645445231375] ERROR (bikestore/20704 on linuxmint): Cannot read properties of undefined (reading 'get')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'get')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'get')
              at Csrf.getCsrfSecret (/.../node_modules/@adonisjs/shield/build/src/csrf.js:132:38)
              at Csrf.handle (/.../node_modules/@adonisjs/shield/build/src/csrf.js:146:39)
              at ShieldMiddleware.handle (/.../node_modules/@adonisjs/shield/build/src/ShieldMiddleware/index.js:74:19)
              at Injector.callAsync (/...node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124:30)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
      "status": 500
    }`

## BONUS (a sample repo to reproduce the issue)
[my repo](https://github.com/navalinovian/bikestores/tree/NodeJSAdonis/backend/AdonisJS/bikestore)

**Comment by navalinovian** [comment]
Thank you so much @thetutlage  for taking your time to answer my trivial question. :clap: :clap:
